"""Verify schema sync fixed

Revision ID: 1bff2dc3dfd0
Revises: 2026020901_decimal_billing
Create Date: 2026-02-09 08:53:16.248182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bff2dc3dfd0'
down_revision: Union[str, None] = '2026020901_decimal_billing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE billingledger ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR")
    op.alter_column('billingledger', 'credits_charged',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.alter_column('billingledger', 'estimated_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'actual_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'delta_credits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'provider_cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'markup_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('billingledger', 'fixed_fee_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'charge_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'credit_value_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_billingledger_idempotency_key ON billingledger (idempotency_key)")
    op.alter_column('credithold', 'reserved_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.execute("ALTER TABLE creditlot ADD COLUMN IF NOT EXISTS source_program_id INTEGER")
    op.execute("ALTER TABLE creditlot ADD COLUMN IF NOT EXISTS source_payment_id VARCHAR")
    op.execute("ALTER TABLE creditlot ADD COLUMN IF NOT EXISTS source_attempt_id VARCHAR")
    op.execute("ALTER TABLE creditlot ADD COLUMN IF NOT EXISTS reason_code VARCHAR")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditlot_source_attempt_id ON creditlot (source_attempt_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditlot_source_payment_id ON creditlot (source_payment_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditlot_source_program_id ON creditlot (source_program_id)")
    op.execute("ALTER TABLE creditlotconsumption ADD COLUMN IF NOT EXISTS ledger_event_id INTEGER")
    op.execute("ALTER TABLE creditlotconsumption ADD COLUMN IF NOT EXISTS attempt_id VARCHAR")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditlotconsumption_attempt_id ON creditlotconsumption (attempt_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditlotconsumption_ledger_event_id ON creditlotconsumption (ledger_event_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_solveroutputattempt_provider_model ON solveroutputattempt (provider_model)")
    op.alter_column('subscription', 'credits_balance',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.alter_column('subscription', 'credits_used_this_period',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'credits_used_this_period',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.alter_column('subscription', 'credits_balance',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.drop_index(op.f('ix_solveroutputattempt_provider_model'), table_name='solveroutputattempt')
    op.drop_index(op.f('ix_creditlotconsumption_ledger_event_id'), table_name='creditlotconsumption')
    op.drop_index(op.f('ix_creditlotconsumption_attempt_id'), table_name='creditlotconsumption')
    op.drop_column('creditlotconsumption', 'attempt_id')
    op.drop_column('creditlotconsumption', 'ledger_event_id')
    op.drop_index(op.f('ix_creditlot_source_program_id'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_source_payment_id'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_source_attempt_id'), table_name='creditlot')
    op.drop_column('creditlot', 'reason_code')
    op.drop_column('creditlot', 'source_attempt_id')
    op.drop_column('creditlot', 'source_payment_id')
    op.drop_column('creditlot', 'source_program_id')
    op.alter_column('credithold', 'reserved_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.drop_index(op.f('ix_billingledger_idempotency_key'), table_name='billingledger')
    op.alter_column('billingledger', 'credit_value_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'charge_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'fixed_fee_usd',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'markup_multiplier',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('billingledger', 'provider_cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'delta_credits',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'actual_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'estimated_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'credits_charged',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.drop_column('billingledger', 'idempotency_key')
    # ### end Alembic commands ###
