"""Verify schema sync fixed

Revision ID: 1bff2dc3dfd0
Revises: 2026020901_decimal_billing
Create Date: 2026-02-09 08:53:16.248182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bff2dc3dfd0'
down_revision: Union[str, None] = '2026020901_decimal_billing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billingledger', sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('billingledger', 'credits_charged',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.alter_column('billingledger', 'estimated_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'actual_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'delta_credits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'provider_cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'markup_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('billingledger', 'fixed_fee_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'charge_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'credit_value_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_billingledger_idempotency_key'), 'billingledger', ['idempotency_key'], unique=True)
    op.alter_column('credithold', 'reserved_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.add_column('creditlot', sa.Column('source_program_id', sa.Integer(), nullable=True))
    op.add_column('creditlot', sa.Column('source_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('creditlot', sa.Column('source_attempt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('creditlot', sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_creditlot_source_attempt_id'), 'creditlot', ['source_attempt_id'], unique=False)
    op.create_index(op.f('ix_creditlot_source_payment_id'), 'creditlot', ['source_payment_id'], unique=False)
    op.create_index(op.f('ix_creditlot_source_program_id'), 'creditlot', ['source_program_id'], unique=False)
    op.add_column('creditlotconsumption', sa.Column('ledger_event_id', sa.Integer(), nullable=True))
    op.add_column('creditlotconsumption', sa.Column('attempt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_creditlotconsumption_attempt_id'), 'creditlotconsumption', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_creditlotconsumption_ledger_event_id'), 'creditlotconsumption', ['ledger_event_id'], unique=False)
    op.create_index(op.f('ix_solveroutputattempt_provider_model'), 'solveroutputattempt', ['provider_model'], unique=False)
    op.alter_column('subscription', 'credits_balance',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    op.alter_column('subscription', 'credits_used_this_period',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'credits_used_this_period',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.alter_column('subscription', 'credits_balance',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.drop_index(op.f('ix_solveroutputattempt_provider_model'), table_name='solveroutputattempt')
    op.drop_index(op.f('ix_creditlotconsumption_ledger_event_id'), table_name='creditlotconsumption')
    op.drop_index(op.f('ix_creditlotconsumption_attempt_id'), table_name='creditlotconsumption')
    op.drop_column('creditlotconsumption', 'attempt_id')
    op.drop_column('creditlotconsumption', 'ledger_event_id')
    op.drop_index(op.f('ix_creditlot_source_program_id'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_source_payment_id'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_source_attempt_id'), table_name='creditlot')
    op.drop_column('creditlot', 'reason_code')
    op.drop_column('creditlot', 'source_attempt_id')
    op.drop_column('creditlot', 'source_payment_id')
    op.drop_column('creditlot', 'source_program_id')
    op.alter_column('credithold', 'reserved_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.drop_index(op.f('ix_billingledger_idempotency_key'), table_name='billingledger')
    op.alter_column('billingledger', 'credit_value_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'charge_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'fixed_fee_usd',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'markup_multiplier',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('billingledger', 'provider_cost_usd',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'delta_credits',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'actual_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'estimated_credits',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'credits_charged',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=False)
    op.drop_column('billingledger', 'idempotency_key')
    # ### end Alembic commands ###
