"""add_is_internal_column

Revision ID: 25e7fcf4d1c5
Revises: f7a9c2d41e11
Create Date: 2026-02-09 21:38:00.133933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25e7fcf4d1c5'
down_revision: Union[str, None] = 'f7a9c2d41e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS is_internal BOOLEAN DEFAULT false NOT NULL')
    op.execute('CREATE INDEX IF NOT EXISTS ix_user_is_internal ON "user" (is_internal)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_internal'), table_name='user')
    op.drop_column('user', 'is_internal')
    # ### end Alembic commands ###
