"""add_is_internal_column

Revision ID: 25e7fcf4d1c5
Revises: f7a9c2d41e11
Create Date: 2026-02-09 21:38:00.133933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25e7fcf4d1c5'
down_revision: Union[str, None] = 'f7a9c2d41e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_internal', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_user_is_internal'), 'user', ['is_internal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_internal'), table_name='user')
    op.drop_column('user', 'is_internal')
    # ### end Alembic commands ###
