"""Add credit program tables

Revision ID: 33045482da8e
Revises: 1bff2dc3dfd0
Create Date: 2026-02-09 08:57:20.323716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33045482da8e'
down_revision: Union[str, None] = '1bff2dc3dfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TABLE IF NOT EXISTS creditprogramdefinition (
        id SERIAL PRIMARY KEY,
        name VARCHAR NOT NULL,
        slug VARCHAR NOT NULL UNIQUE,
        description VARCHAR,
        status VARCHAR NOT NULL,
        monthly_gift_credits NUMERIC(20, 10),
        gift_expiry_window_days INTEGER NOT NULL,
        entitlements JSON,
        purchase_bonus_rules JSON,
        effective_from TIMESTAMP NOT NULL,
        effective_to TIMESTAMP,
        display_price_monthly_usd NUMERIC(20, 10),
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL,
        created_by INTEGER REFERENCES "user"(id)
    )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramdefinition_name ON creditprogramdefinition (name)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramdefinition_status ON creditprogramdefinition (status)")
    op.execute("""
    CREATE TABLE IF NOT EXISTS reconciliationrecord (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES "user"(id),
        cached_balance NUMERIC(20, 10) NOT NULL,
        computed_balance NUMERIC(20, 10) NOT NULL,
        delta NUMERIC(20, 10) NOT NULL,
        auto_fixed BOOLEAN NOT NULL,
        job_run_id VARCHAR NOT NULL,
        created_at TIMESTAMP NOT NULL
    )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_reconciliationrecord_created_at ON reconciliationrecord (created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_reconciliationrecord_job_run_id ON reconciliationrecord (job_run_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_reconciliationrecord_user_id ON reconciliationrecord (user_id)")
    op.execute("""
    CREATE TABLE IF NOT EXISTS creditprogramenrollment (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES "user"(id),
        program_id INTEGER NOT NULL REFERENCES creditprogramdefinition(id),
        status VARCHAR NOT NULL,
        started_at TIMESTAMP NOT NULL,
        ended_at TIMESTAMP,
        paused_at TIMESTAMP,
        last_grant_month VARCHAR,
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL,
        UNIQUE (user_id, program_id)
    )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramenrollment_last_grant_month ON creditprogramenrollment (last_grant_month)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramenrollment_program_id ON creditprogramenrollment (program_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramenrollment_status ON creditprogramenrollment (status)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramenrollment_user_id ON creditprogramenrollment (user_id)")
    op.execute("""
    CREATE TABLE IF NOT EXISTS creditprogramgrantlog (
        id SERIAL PRIMARY KEY,
        enrollment_id INTEGER NOT NULL REFERENCES creditprogramenrollment(id),
        user_id INTEGER NOT NULL REFERENCES "user"(id),
        program_id INTEGER NOT NULL REFERENCES creditprogramdefinition(id),
        grant_month VARCHAR NOT NULL,
        credits_granted NUMERIC(20, 10) NOT NULL,
        credit_lot_id INTEGER NOT NULL REFERENCES creditlot(id),
        expires_at TIMESTAMP NOT NULL,
        created_at TIMESTAMP NOT NULL,
        UNIQUE (enrollment_id, grant_month)
    )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramgrantlog_credit_lot_id ON creditprogramgrantlog (credit_lot_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramgrantlog_enrollment_id ON creditprogramgrantlog (enrollment_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramgrantlog_grant_month ON creditprogramgrantlog (grant_month)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramgrantlog_program_id ON creditprogramgrantlog (program_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_creditprogramgrantlog_user_id ON creditprogramgrantlog (user_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creditprogramgrantlog_user_id'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_program_id'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_grant_month'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_enrollment_id'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_credit_lot_id'), table_name='creditprogramgrantlog')
    op.drop_table('creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramenrollment_user_id'), table_name='creditprogramenrollment')
    op.drop_index(op.f('ix_creditprogramenrollment_status'), table_name='creditprogramenrollment')
    op.drop_index(op.f('ix_creditprogramenrollment_program_id'), table_name='creditprogramenrollment')
    op.drop_index(op.f('ix_creditprogramenrollment_last_grant_month'), table_name='creditprogramenrollment')
    op.drop_table('creditprogramenrollment')
    op.drop_index(op.f('ix_reconciliationrecord_user_id'), table_name='reconciliationrecord')
    op.drop_index(op.f('ix_reconciliationrecord_job_run_id'), table_name='reconciliationrecord')
    op.drop_index(op.f('ix_reconciliationrecord_created_at'), table_name='reconciliationrecord')
    op.drop_table('reconciliationrecord')
    op.drop_index(op.f('ix_creditprogramdefinition_status'), table_name='creditprogramdefinition')
    op.drop_index(op.f('ix_creditprogramdefinition_slug'), table_name='creditprogramdefinition')
    op.drop_index(op.f('ix_creditprogramdefinition_name'), table_name='creditprogramdefinition')
    op.drop_table('creditprogramdefinition')
    # ### end Alembic commands ###
