"""Add credit program tables

Revision ID: 33045482da8e
Revises: 1bff2dc3dfd0
Create Date: 2026-02-09 08:57:20.323716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33045482da8e'
down_revision: Union[str, None] = '1bff2dc3dfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditprogramdefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_gift_credits', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('gift_expiry_window_days', sa.Integer(), nullable=False),
    sa.Column('entitlements', sa.JSON(), nullable=True),
    sa.Column('purchase_bonus_rules', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('display_price_monthly_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditprogramdefinition_name'), 'creditprogramdefinition', ['name'], unique=False)
    op.create_index(op.f('ix_creditprogramdefinition_slug'), 'creditprogramdefinition', ['slug'], unique=True)
    op.create_index(op.f('ix_creditprogramdefinition_status'), 'creditprogramdefinition', ['status'], unique=False)
    op.create_table('reconciliationrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cached_balance', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('computed_balance', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('delta', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('auto_fixed', sa.Boolean(), nullable=False),
    sa.Column('job_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliationrecord_created_at'), 'reconciliationrecord', ['created_at'], unique=False)
    op.create_index(op.f('ix_reconciliationrecord_job_run_id'), 'reconciliationrecord', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliationrecord_user_id'), 'reconciliationrecord', ['user_id'], unique=False)
    op.create_table('creditprogramenrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('last_grant_month', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['creditprogramdefinition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_user_program_active')
    )
    op.create_index(op.f('ix_creditprogramenrollment_last_grant_month'), 'creditprogramenrollment', ['last_grant_month'], unique=False)
    op.create_index(op.f('ix_creditprogramenrollment_program_id'), 'creditprogramenrollment', ['program_id'], unique=False)
    op.create_index(op.f('ix_creditprogramenrollment_status'), 'creditprogramenrollment', ['status'], unique=False)
    op.create_index(op.f('ix_creditprogramenrollment_user_id'), 'creditprogramenrollment', ['user_id'], unique=False)
    op.create_table('creditprogramgrantlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('grant_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits_granted', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('credit_lot_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credit_lot_id'], ['creditlot.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['creditprogramenrollment.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['creditprogramdefinition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'grant_month', name='uq_enrollment_grant_month')
    )
    op.create_index(op.f('ix_creditprogramgrantlog_credit_lot_id'), 'creditprogramgrantlog', ['credit_lot_id'], unique=False)
    op.create_index(op.f('ix_creditprogramgrantlog_enrollment_id'), 'creditprogramgrantlog', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_creditprogramgrantlog_grant_month'), 'creditprogramgrantlog', ['grant_month'], unique=False)
    op.create_index(op.f('ix_creditprogramgrantlog_program_id'), 'creditprogramgrantlog', ['program_id'], unique=False)
    op.create_index(op.f('ix_creditprogramgrantlog_user_id'), 'creditprogramgrantlog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creditprogramgrantlog_user_id'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_program_id'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_grant_month'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_enrollment_id'), table_name='creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramgrantlog_credit_lot_id'), table_name='creditprogramgrantlog')
    op.drop_table('creditprogramgrantlog')
    op.drop_index(op.f('ix_creditprogramenrollment_user_id'), table_name='creditprogramenrollment')
    op.drop_index(op.f('ix_creditprogramenrollment_status'), table_name='creditprogramenrollment')
    op.drop_index(op.f('ix_creditprogramenrollment_program_id'), table_name='creditprogramenrollment')
    op.drop_index(op.f('ix_creditprogramenrollment_last_grant_month'), table_name='creditprogramenrollment')
    op.drop_table('creditprogramenrollment')
    op.drop_index(op.f('ix_reconciliationrecord_user_id'), table_name='reconciliationrecord')
    op.drop_index(op.f('ix_reconciliationrecord_job_run_id'), table_name='reconciliationrecord')
    op.drop_index(op.f('ix_reconciliationrecord_created_at'), table_name='reconciliationrecord')
    op.drop_table('reconciliationrecord')
    op.drop_index(op.f('ix_creditprogramdefinition_status'), table_name='creditprogramdefinition')
    op.drop_index(op.f('ix_creditprogramdefinition_slug'), table_name='creditprogramdefinition')
    op.drop_index(op.f('ix_creditprogramdefinition_name'), table_name='creditprogramdefinition')
    op.drop_table('creditprogramdefinition')
    # ### end Alembic commands ###
