"""phase1_hardening

Revision ID: 9cc1e47ff161
Revises: 
Create Date: 2026-02-07 22:29:28.626948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9cc1e47ff161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_legacy')
    op.add_column('billingledger', sa.Column('finalized_at', sa.DateTime(), nullable=True))
    op.add_column('billingledger', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('billingledger', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'SETTLED'::character varying"))
    op.alter_column('billingledger', 'estimated_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'actual_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'delta_credits',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'fee_tokens_applied',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('billingledger', 'provider_cost_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'markup_multiplier',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('billingledger', 'fixed_fee_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'charge_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'credit_value_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_billingledger_config_version_id'), 'billingledger', ['config_version_id'], unique=False)
    op.create_index(op.f('ix_billingledger_status'), 'billingledger', ['status'], unique=False)
    op.alter_column('chatmessage', 'topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('chatmessage', 'media_url')
    op.alter_column('creditlot', 'lot_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'TOPUP'::character varying"))
    op.alter_column('creditlot', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('creditlot', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('creditlot', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_creditlot_expires_at'), 'creditlot', ['expires_at'], unique=False)
    op.create_index(op.f('ix_creditlot_external_ref'), 'creditlot', ['external_ref'], unique=False)
    op.create_index(op.f('ix_creditlot_lot_type'), 'creditlot', ['lot_type'], unique=False)
    op.create_index(op.f('ix_creditlot_status'), 'creditlot', ['status'], unique=False)
    op.create_index(op.f('ix_creditlot_subscription_id'), 'creditlot', ['subscription_id'], unique=False)
    op.drop_index(op.f('idx_json_schemas_active'), table_name='json_schemas')
    op.drop_index(op.f('idx_json_schemas_schema_id_version'), table_name='json_schemas')
    op.alter_column('llmusageledger', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_llmusageledger_followup_turn_id'), 'llmusageledger', ['followup_turn_id'], unique=True)
    op.alter_column('payment', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'STRIPE'::character varying"))
    op.alter_column('payment', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_payment_created_at'), 'payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_external_id'), 'payment', ['external_id'], unique=False)
    op.create_index(op.f('ix_payment_external_type'), 'payment', ['external_type'], unique=False)
    op.create_index(op.f('ix_payment_idempotency_key'), 'payment', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payment_provider'), 'payment', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_index(op.f('ix_payment_subscription_id'), 'payment', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_foreign_key(None, 'payment', 'subscription', ['subscription_id'], ['id'])
    op.alter_column('prompt_bindings', 'trim_strategy',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NONE', 'TRIM_CONTEXT_FIRST', 'TRIM_USER_FIRST', 'SUMMARIZE_CONTEXT', 'TRIM_EVERYTHING_EXCEPT_PLOT_PLAN', name='trimstrategyenum'),
               existing_nullable=True,
               postgresql_using='trim_strategy::trimstrategyenum')
    op.drop_index(op.f('idx_prompt_bindings_active'), table_name='prompt_bindings')
    op.drop_index(op.f('idx_prompt_templates_active'), table_name='prompt_templates')
    op.drop_index(op.f('idx_prompt_templates_prompt_id_version'), table_name='prompt_templates')
    op.alter_column('providermodelpricing', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_index(op.f('idx_school_normalized_name_trgm'), table_name='school', postgresql_ops={'normalized_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('solveroutputattempt', sa.Column('failure_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE solveroutputattempt SET attempt_id = md5(random()::text || clock_timestamp()::text)::uuid::text WHERE attempt_id IS NULL OR attempt_id = ''")
    op.alter_column('solveroutputattempt', 'attempt_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('solveroutputattempt', 'prompt_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'llm_raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'validation_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'clarification_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'clarification_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'llm_responses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solveroutputattempt', 'validation_events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solveroutputattempt', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_solveroutputattempt_failure_code'), 'solveroutputattempt', ['failure_code'], unique=False)
    op.alter_column('systemerrorentry', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ERROR'::character varying"))
    op.alter_column('systemerrorentry', 'occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('systemerrorentry', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_systemerrorentry_severity'), table_name='systemerrorentry')
    op.create_index(op.f('ix_systemerrorentry_component'), 'systemerrorentry', ['component'], unique=False)
    op.create_index(op.f('ix_systemerrorentry_fingerprint'), 'systemerrorentry', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_systemerrorentry_is_resolved'), 'systemerrorentry', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_systemerrorentry_request_id'), 'systemerrorentry', ['request_id'], unique=False)
    op.create_index(op.f('ix_systemerrorentry_user_id'), 'systemerrorentry', ['user_id'], unique=False)
    op.drop_column('systemerrorentry', 'level')
    op.create_index(op.f('ix_usagelog_user_id'), 'usagelog', ['user_id'], unique=False)
    op.alter_column('user', 'whatsapp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('user_school_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_school_id_fkey'), 'user', 'school', ['school_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user', 'whatsapp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_usagelog_user_id'), table_name='usagelog')
    op.add_column('systemerrorentry', sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_systemerrorentry_user_id'), table_name='systemerrorentry')
    op.drop_index(op.f('ix_systemerrorentry_request_id'), table_name='systemerrorentry')
    op.drop_index(op.f('ix_systemerrorentry_is_resolved'), table_name='systemerrorentry')
    op.drop_index(op.f('ix_systemerrorentry_fingerprint'), table_name='systemerrorentry')
    op.drop_index(op.f('ix_systemerrorentry_component'), table_name='systemerrorentry')
    op.create_index(op.f('ix_systemerrorentry_severity'), 'systemerrorentry', ['severity'], unique=False)
    op.alter_column('systemerrorentry', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('systemerrorentry', 'occurrence_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('systemerrorentry', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ERROR'::character varying"))
    op.drop_index(op.f('ix_solveroutputattempt_failure_code'), table_name='solveroutputattempt')
    op.alter_column('solveroutputattempt', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('solveroutputattempt', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'validation_events',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solveroutputattempt', 'llm_responses',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('solveroutputattempt', 'clarification_history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'clarification_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('solveroutputattempt', 'validation_errors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'llm_raw_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'prompt_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('solveroutputattempt', 'attempt_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('solveroutputattempt', 'failure_code')
    op.create_index(op.f('idx_school_normalized_name_trgm'), 'school', ['normalized_name'], unique=False, postgresql_ops={'normalized_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('providermodelpricing', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_index(op.f('idx_prompt_templates_prompt_id_version'), 'prompt_templates', ['prompt_id', 'version'], unique=True)
    op.create_index(op.f('idx_prompt_templates_active'), 'prompt_templates', ['prompt_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_prompt_bindings_active'), 'prompt_bindings', ['tier', 'mode', 'is_active'], unique=False)
    op.alter_column('prompt_bindings', 'trim_strategy',
               existing_type=sa.Enum('NONE', 'TRIM_CONTEXT_FIRST', 'TRIM_USER_FIRST', 'SUMMARIZE_CONTEXT', 'TRIM_EVERYTHING_EXCEPT_PLOT_PLAN', name='trimstrategyenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_subscription_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_provider'), table_name='payment')
    op.drop_index(op.f('ix_payment_idempotency_key'), table_name='payment')
    op.drop_index(op.f('ix_payment_external_type'), table_name='payment')
    op.drop_index(op.f('ix_payment_external_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_created_at'), table_name='payment')
    op.alter_column('payment', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payment', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'STRIPE'::character varying"))
    op.drop_index(op.f('ix_llmusageledger_followup_turn_id'), table_name='llmusageledger')
    op.alter_column('llmusageledger', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('idx_json_schemas_schema_id_version'), 'json_schemas', ['schema_id', 'version'], unique=True)
    op.create_index(op.f('idx_json_schemas_active'), 'json_schemas', ['schema_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_creditlot_subscription_id'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_status'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_lot_type'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_external_ref'), table_name='creditlot')
    op.drop_index(op.f('ix_creditlot_expires_at'), table_name='creditlot')
    op.alter_column('creditlot', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('creditlot', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('creditlot', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('creditlot', 'lot_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'TOPUP'::character varying"))
    op.add_column('chatmessage', sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('chatmessage', 'topics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_billingledger_status'), table_name='billingledger')
    op.drop_index(op.f('ix_billingledger_config_version_id'), table_name='billingledger')
    op.alter_column('billingledger', 'credit_value_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'charge_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'fixed_fee_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'markup_multiplier',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('billingledger', 'provider_cost_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'fee_tokens_applied',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('billingledger', 'delta_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'actual_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'estimated_credits',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('billingledger', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'SETTLED'::character varying"))
    op.drop_column('billingledger', 'updated_at')
    op.drop_column('billingledger', 'finalized_at')
    op.create_table('school_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('province_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade_range', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
