"""add_admin_audit_log_table

Revision ID: e39acf3d7451
Revises: 33045482da8e
Create Date: 2026-02-09 09:19:33.437292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e39acf3d7451'
down_revision: Union[str, None] = '33045482da8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS adminauditlog (
            id SERIAL PRIMARY KEY,
            admin_user_id INTEGER NOT NULL REFERENCES "user" (id),
            action VARCHAR NOT NULL,
            entity_type VARCHAR NOT NULL,
            entity_id VARCHAR,
            before_json JSON,
            after_json JSON,
            reason VARCHAR,
            ip_address VARCHAR,
            user_agent VARCHAR,
            idempotency_key VARCHAR,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_adminauditlog_action ON adminauditlog (action)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adminauditlog_admin_user_id ON adminauditlog (admin_user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adminauditlog_created_at ON adminauditlog (created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adminauditlog_entity_type ON adminauditlog (entity_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_adminauditlog_idempotency_key ON adminauditlog (idempotency_key)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adminauditlog_idempotency_key'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_entity_type'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_created_at'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_admin_user_id'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_action'), table_name='adminauditlog')
    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
