"""add_admin_audit_log_table

Revision ID: e39acf3d7451
Revises: 33045482da8e
Create Date: 2026-02-09 09:19:33.437292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e39acf3d7451'
down_revision: Union[str, None] = '33045482da8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminauditlog_action'), 'adminauditlog', ['action'], unique=False)
    op.create_index(op.f('ix_adminauditlog_admin_user_id'), 'adminauditlog', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_adminauditlog_created_at'), 'adminauditlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_adminauditlog_entity_type'), 'adminauditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_adminauditlog_idempotency_key'), 'adminauditlog', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adminauditlog_idempotency_key'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_entity_type'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_created_at'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_admin_user_id'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_action'), table_name='adminauditlog')
    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
